[package]
name = "point-generator"
edition = "2018"
version = "0.0.1"
authors = [
  "Brandon Thomas <bt@brand.io>",
  "Brandon Thomas <echelon@gmail.com>",
]
publish = false

[[bin]]
name = "point-generator"
path = "src/main.rs"

[dependencies]
bytes = "1.0.1"
byteorder = "1.4.2"
rand = "0.8.2"
zmq = { version = "0.9", features = ['vendored'] }
#zeromq = "0.2.0" # Doesn't compile. Complains about Rust issue #54727
