[package]
name = "bevy-facial-mocap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]

[dependencies]
bevy = { version = "0.12", default-features = false, features = ["bevy_pbr", "bevy_render", "bevy_asset", "animation", "bevy_animation"]}
serde = { version = "1", features = ["derive"] }
csv = "1.3"
serde_json = "1"
itertools = "0.12"

[dev-dependencies]
bevy = { version = "0.12", default-features = true, features = ["file_watcher"]}
bevy-inspector-egui = "0.22"
